# Default values for src.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: src
replicaCount: 1
image:çz
  repository: 
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
service:
  type: ClusterIP
  port: 80

service:
  type: ClusterIP
  port: 5000

probes:
  enabled: false

ingress:
  enabled: false
  annotations:
    # kubernetes.io/tls-acme: "true"

